site_name: pybelugaxl
site_description: Documentation for pybelugaxl project
repo_url: https://github.com/TGA25dev/pybelugaxl
site_url: https://tga25dev.github.io/pybelugaxl/
theme:
  name: material
  features:
    - header.autohide
    - navigation.footer

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: indigo
  

markdown_extensions:
  - attr_list
  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/TGA25dev/pybelugaxl